services:
  db:
    image: postgres:14
    container_name: trading-card-db
    ports:
      - 5440:5432
    environment:
      - POSTGRES_DB=trading-card
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  card-catalog:
    image: bolszowka/card-catalog:0.0.1-SNAPSHOT
    container_name: card-catalog
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/trading-card?currentSchema=card-catalog